media:
  input: public/images
  output: /roadmap/images

content:
  - name: ceo
    label: CEO Message
    path: src/content/homepage
    filename: ceo
    type: file
    fields:
      - name: name
        label: Name
        type: string
      - name: job_title
        label: Job Title
        type: string
      - name: photo
        label: Photo
        type: image
      - name: description
        label: Message
        type: text

  - name: themes
    label: Themes for 2026
    path: src/content/homepage
    filename: themes
    type: file
    fields:
      - name: themes
        label: Themes
        type: object
        list:
          collapsible:
            summary: "{title}"
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text
          - name: image
            label: Image
            type: image

  - name: product-groups
    label: Product Groups
    path: src/content
    filename: product-groups
    type: file
    fields:
      - name: groups
        label: Groups
        type: object
        list:
          collapsible:
            summary: "{label}"
        fields:
          - name: id
            label: ID
            type: string
          - name: label
            label: Label
            type: string
          - name: teams
            label: Teams
            type: object
            list:
              collapsible:
                summary: "{name}"
            fields:
              - name: name
                label: Name
                type: string
              - name: slug
                label: Slug
                type: string
              - name: icon
                label: Icon Filename
                type: string

  - name: teams
    label: Teams
    path: src/content/teams
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: hero_image
        label: Hero Image
        type: string

      - name: team_members
        label: Team Members
        type: object
        list:
          collapsible:
            summary: "{name}"
        fields:
          - name: name
            label: Name
            type: string
          - name: title
            label: Title
            type: string
          - name: photo
            label: Photo
            type: image
            options:
              path: team-members

      - name: gantt_items
        label: Roadmap Items
        type: object
        list:
          collapsible:
            summary: "{title}"
        fields:
          - name: title
            label: Title
            type: string
          - name: start_date
            label: Start Date
            type: date
            options:
              format: yyyy-MM-dd
          - name: end_date
            label: End Date
            type: date
            options:
              format: yyyy-MM-dd

      - name: goals
        label: Goals
        type: object
        list:
          collapsible:
            summary: "{headline}"
        fields:
          - name: headline
            label: Headline
            type: string
          - name: description
            label: Description
            type: string

      - name: key_initiatives
        label: Key Initiatives
        type: object
        list:
          collapsible:
            summary: "{heading}"
        fields:
          - name: heading
            label: Heading
            type: string
          - name: description
            label: Description
            type: text
